version: '3.8'

services:
  data_warehouse:
    image: postgres:15-alpine
    container_name: geci_warehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data #
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio: # Data Lake Katmanı
    image: minio/minio:latest
    container_name: geci_datalake
    ports:
      - "9000:9000" # API erişimi
      - "9001:9001" # Arayüz (Console) erişimi
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  streamlit_app:
    build: .
    container_name: geci_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      data_warehouse:
        condition: service_healthy
    env_file: .env #

volumes:
  postgres_data:
  minio_data: